wandb_version: 1

model:
  desc: null
  value: LLAMA_HF_WEIGHTS_LOCATION
dataset:
  desc: null
  value: c4
seed:
  desc: null
  value: 0
nsamples:
  desc: null
  value: 128
percdamp:
  desc: null
  value: 0.01
sparsity:
  desc: null
  value: 0.5
prunen:
  desc: null
  value: 0
prunem:
  desc: null
  value: 0
blocksize:
  desc: null
  value: 128
gmp:
  desc: null
  value: false
wbits:
  desc: null
  value: 16
minlayer:
  desc: null
  value: -1
maxlayer:
  desc: null
  value: 1000
prune_only:
  desc: null
  value: ''
invert:
  desc: null
  value: false
save:
  desc: null
  value: output/llama_0.5
true_sequential:
  desc: null
  value: false
log_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701992824.645608
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 16
      - 23
      4: 3.11.5
      5: 0.15.3
      6: 4.31.0
      8:
      - 5
